spring:
  datasource:
    url: jdbc:postgresql://prod-db-server:5432/warehouse_ems_prod
    username: prod_user
    password: prod_secure_pass
  jpa:
    show-sql: false
logging:
  level:
    root: INFO
