# Production Profile Properties

spring.datasource.url=jdbc:postgresql://prod-db-server:5432/warehouse_ems_prod
spring.datasource.username=prod_user
spring.datasource.password=prod_pass

logging.level.org.springframework=INFO
logging.level.com.warehouse.ems=INFO

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

management.endpoints.web.exposure.include=health,info
