spring:
  application:
    name: warehouse-ems
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/warehouse_ems}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
security:
  auth:
    type: ${AUTH_TYPE:OAUTH2}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
