spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse_ems_dev
    username: ems_dev
    password: ems_dev_password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

logging:
  level:
    root: DEBUG
