spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wms_dev
    username: wms_dev_user
    password: wms_dev_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8081

logging:
  level:
    root: DEBUG
    org.springframework.security: DEBUG
