spring:
  datasource:
    url: jdbc:postgresql://prod-db:5432/warehouse
    username: warehouse_user
    password: strongpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  profiles:
    active: prod
server:
  port: 8080
logging:
  level:
    root: WARN
    org.springframework.web: INFO
